version: '3.9'
# uwsgi --http :8000 --module django_project.wsgi
services:
  app:
    build:
      context: .
    
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
      - ./data/web:/vol/web
    command: >
      sh -c "python manage.py wait_for_db &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "
    
    environment: 
      - DEBUG=0
      - SECRET_KEY=osthesecret
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=devpass
      - CDB_HOST=172.21.12.188
      - CDB_NAME=vscrmnew
      - CDB_USER=vbs-dsk0098
      - CDB_PASS=Admin@optiplex
      - ALLOWED_HOSTS=127.0.0.1
      - CDB_PORT=3306
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    environment: 
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=devpass