# Generated by Django 2.2 on 2021-06-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MsiFilters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_name', models.CharField(max_length=120)),
                ('filter_date', models.DateTimeField(auto_now=True)),
                ('filter_data', models.TextField()),
            ],
        ),
    ]
